### ISSUE TITLE
schemas should be versioned

### ISSUE THREAD

**Issue by shazron** [adobe/aio-lib-console-project-installation#1]
We should discuss how schemas are versioned

**Comment by roribio** [comment]
Schemas now have a numerical identifier, like this: https://github.com/adobe/aio-lib-console-project-installation/blame/0b513e93546ff7ebb55f1d2ea1d100c9b5bf96c9/schema/template.schema.json#L3

Is this sufficient or do you have something else in mind?

**Comment by shazron** [comment]
LGTM
